### ISSUE TITLE
Handle PAX headers in tar files

### ISSUE THREAD

**Issue by acharlieh** [cerner/cerner_splunk#143]
Pax headers have entity types g (global) and x .... As bsdtar (MacOS) and gnutar in posixmode both could, we probably should support them.

Some links: 
https://www.gnu.org/software/tar/manual/html_section/tar_71.html#SEC147
https://www.ibm.com/support/knowledgecenter/SSLTBW_1.13.0/com.ibm.zos.r13.bpxa500/pxarchfm.htm
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/pax.html#tag_20_92_13_03

**Comment by gravesb** [comment]
In reference to rubygems/rubygems#2213, we likely need to re-implement the tarball library using something other than the `Gem::Package::TarReader`. The issue was worked around elsewhere in chef via an update to mixlib-archive.  We should look at using that library instead or coding directly against ffi-libarchive ourselves.

https://github.com/chef/mixlib-archive/commit/3b2b0f241bb665328c7f42e8426fd59f5f5445d1

**Comment by gravesb** [comment]
We updated to use mixlib-archive in 2.33.0.  Closing since that should resolve this issue.
